import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import styled from "styled-components";
import React from "react";
import HeroSection from "../sections/HeroSection";
import PeersSection from "../sections/PeersSection";
import FlatsSection from "../sections/FlatsSection";
import WhyUsSection from "../sections/WhyUsSection";
import PartnerSection from "../sections/PartnersSection";

export default function Home() {
  let { t } = useTranslation();
  return (
    <Wrapper>
      <Head>
        <title>Roompeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionWrapper>
        <HeroSection />
        <FlatsSection />
        <PeersSection />
        <WhyUsSection />
        <PartnerSection />
      </SectionWrapper>
    </Wrapper>
  );
}

const Wrapper = styled.div`
  min-height: 100vh;
  overflow-x: hidden;
`;

const SectionWrapper = styled.div``;
