import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import styled from "styled-components";
import React from "react";
import HeroSection from "../sections/HeroSection";
import FeaturedSection from "../sections/FeaturedSection";

export default function Home() {
  let { t } = useTranslation();
  return (
    <Wrapper>
      <Head>
        <title>Roompeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionWrapper>
        <HeroSection />
        <FeaturedSection />
      </SectionWrapper>
    </Wrapper>
  );
}

const Wrapper = styled.div`
  height: 100vh;
`;

const SectionWrapper = styled.div``;
