import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import LandingPage from "../components/ui/Landing";
import styled from "styled-components";
import React, { useState, useEffect } from "react";
import Home from "../components/ui/Home";
import { firebaseInstance } from "../model/firebase-config";

export default function HomePage() {
  let { t } = useTranslation();
  const [currentUser, setCurrentUser] = useState(null);

  useEffect(() => {
    if (firebaseInstance) {
      firebaseInstance.auth().onAuthStateChanged((authUser) => {
        if (authUser) {
          setCurrentUser(authUser);
        } else {
          setCurrentUser(null);
        }
      });
    }
  }, []);

  return (
    <Wrapper>
      <Head>
        <title>Roompeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {currentUser ? <Home /> : <LandingPage />}
    </Wrapper>
  );
}

const Wrapper = styled.div``;
