import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import styled from "styled-components";
import Home from "../components/ui/Home";

export default function HomePage() {
  let { t } = useTranslation();

  return (
    <Wrapper>
      <Head>
        <title>Roompeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </Wrapper>
  );
}

const Wrapper = styled.div``;
