import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import styled from "styled-components";
import Home from "../components/ui/Home";
import { useAuth } from "../context/Auth";
import LoadingPage from "../components/ui/LoadingPage";

export default function HomePage() {
  let { t } = useTranslation();
  let { user } = useAuth();

  return (
    <Wrapper>
      <Head>
        <title>Roompeer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? <Home /> : <LoadingPage />}
    </Wrapper>
  );
}

const Wrapper = styled.div``;
